
# List of knows DNS types
DNS_RECORD_TYPES = {
    'A': {'code': 1, 'desc': 'Address'},
    'AAAA': {'code': 28, 'desc': 'IPv6 Address'},
    'AFSDB': {'code': 18, 'desc': 'AFS DataBase'},
    'APL': {'code': 42, 'desc': 'Address Prefix List'},
    'CAA': {'code': 257, 'desc': 'Certification Authority Authorization'},
    'CDNSKEY': {'code': 60, 'desc': 'Child DNSKEY'},
    'CDS': {'code': 59, 'desc': 'Child DS'},
    'CERT': {'code': 37, 'desc': 'CERTificate'},
    'CNAME': {'code': 5, 'desc': 'Canonical NAME'},
    'DHCID': {'code': 49, 'desc': 'DHCP IDentifier'},
    'DLV': {'code': 32769, 'desc': 'Dnssec Lookaside Validation'},
    'DNAME': {'code': 39, 'desc': 'Delegation NAME'},
    'DNSKEY': {'code': 48, 'desc': 'DNS KEY'},
    'DS': {'code': 43, 'desc': 'Delegation Signer'},
    'HIP': {'code': 55, 'desc': 'Host Identity Protocol'},
    'IPSECKEY': {'code': 45, 'desc': 'IPSEC KEY'},
    'KEY': {'code': 25, 'desc': 'KEY'},
    'KX': {'code': 36, 'desc': 'Key eXchanger'},
    'LOC': {'code': 29, 'desc': 'LOCation'},
    'MX': {'code': 15, 'desc': 'Mail eXchange'},
    'NAPTR': {'code': 35, 'desc': 'Naming Authority PoinTeR'},
    'NS': {'code': 2, 'desc': 'Name Server'},
    'NSEC': {'code': 47, 'desc': 'Next-SECure'},
    'NSEC3': {'code': 50, 'desc': 'NSEC version 3'},
    'NSEC3PARAM': {'code': 51, 'desc': 'NSEC3 PARAMeters'},
    'PTR': {'code': 12, 'desc': 'PoinTeR'},
    'RRSIG': {'code': 46, 'desc': 'DNSSEC signature'},
    'RP': {'code': 17, 'desc': 'Responsible Person'},
    'SIG': {'code': 24, 'desc': 'SIGnature'},
    'SOA': {'code': 6, 'desc': 'Start Of [a zone of] Authority'},
    'SRV': {'code': 33, 'desc': 'SeRVice locator'},
    'SSHFP': {'code': 44, 'desc': 'SSH public key FingerPrint'},
    'TA': {'code': 32768, 'desc': 'dnssec Trust Authorities'},
    'TKEY': {'code': 249, 'desc': 'Secret KEY'},
    'TLSA': {'code': 52, 'desc': 'TLSA certificate association'},
    'TSIG': {'code': 250, 'desc': 'Transaction SIGnature'},
    'TXT': {'code': 16, 'desc': 'TeXT'},
    'AXFR': {'code': 252, 'desc': 'Authoritative zone tranXFeR'},
    'IXFR': {'code': 251, 'desc': 'Incremental zone TranXTeR'},
    'OPT': {'code': 41, 'desc': 'OPTion'},
    'NIMLOC': {'code': 32, 'desc': 'NIMLOC'},
    'HINFO': {'code': 13, 'desc': 'Host INFOrmation'},
    'X25': {'code': 19, 'desc': 'X.25 PSDN address'},
    'ISDN': {'code': 20, 'desc': 'Integrated Services Digital Network'},
    'RT': {'code': 21, 'desc': 'Route Through'},
    'NSAP': {'code': 22, 'desc': 'Network Service Access Point'},
    'NSAP-PTR': {'code': 23, 'desc': 'NSAP to PoinTeR'},
    'EID': {'code': 31, 'desc': 'Endpoint IDentifier'},
    'ATMA': {'code': 34, 'desc': 'Asynchronous Transfer Mode Address'},
    'OPENPGPKEY': {'code': 0, 'desc': 'OPEN PGP KEY'},
    # Obsolete record types
    'MD': {'code': 3, 'desc': 'MD Obsolete replace by MX'},
    'MF': {'code': 4, 'desc': 'MF Obsolete replace by MX'},
    'MAILA': {'code': 254, 'desc': 'MAILA Obsolete replace by MX'},
    'MB': {'code': 7, 'desc': 'MB Obsolete replace by SMTP VRFY'},
    'MG': {'code': 8, 'desc': 'MG Obsolete replace by SMTP EXPN'},
    'MR': {'code': 9, 'desc': 'MR Obsolete replace by SMTP 551 error'},
    'MINFO': {'code': 14, 'desc': 'MINFO Obsolete'},
    'MAILB': {'code': 253, 'desc': 'MAILB Obsolete'},
    'WKS': {'code': 11, 'desc': 'WKS Obsolete'},
    'NB': {'code': 32, 'desc': 'NB Obsolete replace by NIMLOC'},
    'NBSTAT': {'code': 33, 'desc': 'NBSTAT Obsolete replace by SRV'},
    'SPF': {'code': 99, 'desc': 'SPF Obsolete must use TXT'},
    'GPOS': {'code': 27, 'desc': 'GPOS Obsolete replace by LOC'},
    # Not supported record types
    'UINFO': {'code': 100, 'desc': ''},
    'UID': {'code': 101, 'desc': ''},
    'GID': {'code': 102, 'desc': ''},
    'UNSPEC': {'code': 103, 'desc': ''},
}
